---
- set_fact:
    kongblitz_timestamps_configmap:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: "{{ timestamp_configmap_name }}"
        namespace: "{{ meta.namespace }}"
    kongblitz_timestamp_data: 
      data: {}
    operator_reconciled: false
    operator_conditions: []

- block:

  - name: "Set Reconciling state"
    k8s_status:
      api_version: konveyor.openshift.io/v1alpha1
      kind: KongBlitz
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      force: true
      conditions: "{{ operator_conditions }}"
      status:
        phase: Reconciling

  - name: "Reading timestamp configmap"
    k8s_info:
      kind: ConfigMap
      namespace: "{{ meta.namespace }}"
      name: "{{ timestamp_configmap_name }}"
    register: blitz_timestamps

  - include_tasks: process_resource.yml
    loop: "{{ resources }}"
    loop_control:
      loop_var: current_res

  - name: "Updating timestamp configmap"
    k8s:
      kind: ConfigMap
      definition: "{{ kongblitz_timestamps_configmap | combine(kongblitz_timestamp_data, recursive=true) }}"

  - set_fact:
      operator_reconciled: true

  always:
  - k8s_status:
      api_version: konveyor.openshift.io/v1alpha1
      kind: KongBlitz
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      conditions: "{{ operator_conditions }}"
      status:
        phase: Reconciled
    when: operator_reconciled

  - k8s_status:
      api_version: konveyor.openshift.io/v1alpha1
      kind: KongBlitz
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      conditions: "{{ operator_conditions }}"
      status:
        phase: Failed
    when: not operator_reconciled
