apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongblitzs.konveyor.openshift.io
spec:
  group: konveyor.openshift.io
  names:
    kind: KongBlitz
    listKind: KongBlitzList
    plural: kongblitzs
    singular: kongblitz
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
