---
- block:
  - set_fact:
      kong_target_ns: "kong-{{ ns_prefix }}-{{ ns_index }}"

  - debug:
      msg: "Processing namespace {{ kong_target_ns }}"

  - name: "Destroy kube kong instance namespaces"
    k8s:
      kind: Namespace
      state: absent
      name: "{{ kong_target_ns }}"
