---
- set_fact:
    kong_requested_resource:
      kind: "{{ kong_resource.get('kind', 'kindNotFound') | string | lower }}"
      count: "{{ kong_resource.get('count', 1) | int }}"
      definition: "{{ kong_resource.get('definition', {}) }}"

- when:
  - (resource_discovery_results.resources | d([]) | length | int) < (kong_requested_resource.count | int)
  ignore_errors: true
  block:
  - name: "Tearing down resources"
    vars:
      kong_metadata: 
        metadata:
          namespace: "{{ meta.namespace }}"
      range_start: 0
      resource_definition: "{{ kong_requested_resource.definition if kong_requested_resource.definition != {} 
        else supported_resources[kong_requested_resource.kind] }}"
    k8s:
      state: absent
      definition: "{{ lookup('template', 'manifest.yml.j2') }}"
    register: resource_generation_results