---
- set_fact:
    kong_requested_resource:
      kind: "{{ kong_resource.get('kind', 'kindNotFound') | string | lower }}"
      count: "{{ kong_resource.get('count', 1) | int }}"
      definition: "{{ kong_resource.get('definition', {}) }}"

- set_fact:
    requested_custom_resource: "{{ kong_requested_resource.definition != {} }}"

- when:
  - not requested_custom_resource|bool
  set_fact:
    requested_resource_supported: "{{ kong_requested_resource.kind in supported_resources.keys() }}"

- when:
  - not requested_custom_resource|bool
  - not requested_resource_supported|bool
  debug:
    msg: "Requested resource {{ kong_requested_resource.kind }} not a part of default KongArmy. Please specify a definition field."
  
  # TODO : update the CR status to notify users about the wrong definition / kind

- ignore_errors: true
  block:
  - name: "Checking whether current resource exists"
    vars:
      kind: "{{ kong_requested_resource.kind if not requested_custom_resource
        else kong_requested_resource.definition.kind }}"
      api_version: "{{ supported_resources[kong_requested_resource.kind].apiVersion if not requested_custom_resource
        else kong_requested_resource.definition.apiVersion }}"
    k8s_info:
      kind: "{{ kind }}"
      namespace: "{{ meta.namespace }}"
      api_version: "{{ api_version }}"
      label_selectors:
      - "ownedByKind=KongArmy"
      - "ownedByName={{ meta.name }}"
    register: resource_discovery_results

- debug:
    msg: "PG : disc-res {{ resource_discovery_results }}"

- debug:
    msg: "{{ (resource_discovery_results.resources | d([]) | length | int) }} - {{ (kong_requested_resource.count | int) }}"

- when:
  - (resource_discovery_results.resources | d([]) | length | int) < (kong_requested_resource.count | int)
  ignore_errors: true
  block:
  - name: "Generating resources"
    vars:
      range_start: 0
      range_end: "{{ kong_requested_resource.count|int }}"
      resource_definition: "{{ kong_requested_resource.definition if requested_custom_resource 
        else supported_resources[kong_requested_resource.kind] }}"
    k8s:
      state: present
      definition: "{{ lookup('template', 'manifest.yml.j2') }}"
    register: resource_generation_results
  
  # TODO : gather results and update the CR status field

- when:
  - (resource_discovery_results.resources | d([]) | length | int) > (kong_requested_resource.count | int)
  ignore_errors: true
  block:
  - name: "Reconciling the count for current resource"
    vars:
      range_start: "{{ (kong_requested_resource.count | int) | abs }}"
      range_end: "{{ (resource_discovery_results.resources | d([]) | length | int) }}"
      resource_definition: "{{ kong_requested_resource.definition if requested_custom_resource 
        else supported_resources[kong_requested_resource.kind] }}"
    k8s:
      state: absent
      definition: "{{ lookup('template', 'manifest.yml.j2') }}"
    register: resource_count_reconciliation_results
  
  # TODO: update the CR field