---
- set_fact:
    kong_metadata:
      metadata:
        namespace: "{{ meta.namespace }}"
        labels:
          ownedByKind: KongArmy
          ownedByName: "{{ meta.name }}"
    
    operator_reconciled: false
    operator_conditions: []

- block:
  - name: Set Reconciled state
    operator_sdk.util.k8s_status:
      api_version: konveyor.openshift.io/v1alpha1
      kind: KongArmy
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      force: true
      conditions: "{{ operator_conditions }}"
      status:
        phase: Reconciling

  - when: not teardown|bool
    tags:
    - resource_generation
    block:
    - include_tasks: "kong_res_gen.yml"
      loop: "{{ requested_resources }}"
      loop_control:
        loop_var: kong_resource

  - when: teardown|bool
    tags:
    - resource_generation
    block:
    - include_tasks: "kong_res_clean.yml"
      loop: "{{ requested_resources }}"
      loop_control:
        loop_var: kong_resource