---
kong_config:
  - namespaces:
    - kong-army-1
    - kong-army-2
    - kong-army-3
    kong_army:
      teardown: false
      requested_resources:
      - count: 10
        kind: Secret
      - count: 10
        kind: ConfigMap
  - namespaces:
    - kong-army-4
    kong_army:
      teardown: false
      requested_resources:
      - count: 10
        kind: Pod
